### PR TITLE
Made settings generic

### PR DESCRIPTION
**Pull request by fabianofrancesconi**
This way when upgrading the application you don't lose previous settings

### CODE REVIEW

**Comment by hunterjm** [comment]
That's pretty cool.  I'm assuming the application will have access to write to the user's directory and if the folders don't exist, it will create them automatically?

Also, would it be better to do `futgui/config` instead of `config/futgui`?  Also, should we think of writing the cookies file there as well so you don't have to re-authenticate with EA on upgrade either?

**Comment by fabianofrancesconi** [comment]
`.config` is a standard for the location of configuration files in the python world (e.g., Deluge or Transmission). I have to check whether the directory is created. Also we could think about writing the cookies but I would rather give priority to be able to buy consumables.

**Comment by hunterjm** [comment]
I'm ok with .config, can you double check if the directory gets created. Then I'll merge. Thanks again for helping add features.

**Comment by hunterjm** [comment]
Would you mind adding logic to create directories if they don't exist?  I think it would be good to handle situations where the user doesn't have write permission to the `.config` directory as well so we can handle the error gracefully instead of the program just hanging with an exception.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tkinter/__init__.py", line 1549, in __call__
    return self.func(*args)
  File "/Users/jason/futgui/frames/login.py", line 103, in login
    with open(expanduser("~") + '/.config/futgui/login.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jason/.config/futgui/login.json'
```

**Comment by fabianofrancesconi** [comment]
Yes, I will.. :)

**Comment by fabianofrancesconi** [comment]
@hunterjm done, I hope you don't mind the new logic I have inserted as well

**Comment by hunterjm** [comment]
@elbryan: Looks good.  I'm going to pull your branch down and run through it tonight.  I have a PR in to the core fut library that I want merged and on pip before I bundle another release.  I'll plan on merging this in sometime tomorrow.

**Pull request merged**
